#pragma once

// Held items on the real body (task 14.7) — the thing no character in this
// engine has ever actually done.
//
// A sword appeared in every early capture, so it was reasonable to assume held
// items worked. They did not. That sword was generated by `buildHumanoidVisual`
// — the v1 box rig — as a rigid part bolted to a joint. When the body became an
// imported skinned mesh, `buildPosedCharacter` took over and skipped held items
// outright (`if (garment.vertices.empty()) continue; // held items are not
// garments`), and so did the device build. Nothing regressed; the feature was
// never there on this path. Phase 14's whole archetype library animates hands
// that hold nothing.
//
// Held items are NOT garments and deliberately do not go near the fitting
// pipeline (CHARACTERS.md §6.1). A garment deforms with the skin; a sword is
// rigid and simply follows a joint. So the mechanism is small:
//
//     characterLocal = jointWorld[anchor] · anchorOffset · gripOffset · vertex
//
// one matrix chain per item per frame, no skinning, no binding, no re-fit. The
// item's mesh is an ordinary static `.mgemesh`; what makes it a held item is a
// `.mgewear` row that says `held true` and names an anchor.
//
// Two things this file deliberately does not decide:
//   * WHICH item a character is holding, and what using it does — that is the
//     `ItemUse` seam, gameplay's (task 14.5).
//   * How the arm MOVES while holding it — that is the archetype library
//     (task 14.2), animation's. Grip is declared here because the item is what
//     knows it; the motion it selects belongs to that side.

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "mge/character/humanoid.h"
#include "mge/core/math.h"
#include "mge/graphics/mesh_data.h"

namespace mge {

struct WearableDef;

// ---------------------------------------------------------- attachment -----

// Where on the body an item can sit. These are the sockets CHARACTERS.md §6.1
// calls for: the hands an item is held in, and the places a sheathed one rests.
//
// Each resolves to a joint plus a local offset, derived from the rig so it
// follows a variant's proportions for free — a tall character's grip point is
// where that character's hand actually is, with no per-variant data. When the
// body ships explicit anchors (B-19, task 13.9) they replace the derivation
// behind this same enum, exactly as the body's vertex groups will replace
// `permittedBindRegions`.
enum class AttachPoint : uint8_t {
    HandR = 0,
    HandL,
    Back,
    HipL,
    HipR,
    Count,
};
constexpr size_t kAttachPointCount = static_cast<size_t>(AttachPoint::Count);

const char* attachPointName(AttachPoint point);
bool attachPointFromName(const char* name, AttachPoint& out);

// The joint an attachment hangs from.
Joint attachPointJoint(AttachPoint point);

// The attachment's transform in CHARACTER-LOCAL space for one posed variant.
// `jointWorld` is what `evaluatePose(buildSkeleton(variant), pose, ...)`
// produces — the same joint transforms the skinning palette is built from, so
// a held item lands exactly where the skinned hand does.
Mat4 attachPointTransform(AttachPoint point, const HumanoidVariant& variant,
                          const Mat4 jointWorld[kJointCount]);

// ---------------------------------------------------------------- grip -----

// How many hands an item asks for (CHARACTERS.md §6.1). The engine uses this
// to decide slot occupancy; the animation side uses the same word to choose
// the motion and the joint mask, which is why the item declares it once.
enum class GripType : uint8_t {
    OneHanded = 0,
    TwoHanded,
    Versatile,  // usable either way; the wielder's free hand decides
    Count,
};

const char* gripTypeName(GripType grip);
bool gripTypeFromName(const char* name, GripType& out);

// Everything a held item declares beyond its mesh. Parsed from the same
// `.mgewear` file a garment uses — `held true` selects this half.
struct HeldItemDef {
    GripType grip = GripType::OneHanded;
    AttachPoint drawn = AttachPoint::HandR;  // where it sits in hand
    AttachPoint sheathed = AttachPoint::Back;
    bool sheathable = true;
    Vec3 gripOffset{0, 0, 0};   // metres, in anchor-local space
    Vec3 gripRotation{0, 0, 0};  // degrees, applied X then Y then Z
};

// The grip transform: where the item's own origin sits relative to the
// anchor. Item grip meets hand point, so no per-item animation is authored
// (CHARACTERS.md §6.1).
Mat4 gripTransform(const HeldItemDef& item);

// ------------------------------------------------------------ placing -----

// One held item, ready to draw: its mesh already transformed into
// character-local space, next to the colour it renders with.
struct HeldItemPlacement {
    MeshData mesh;
    float color[4] = {1, 1, 1, 1};
};

// The static mesh a held item's `.mgewear` names, loaded once and shared
// process-wide. Empty when the asset is missing — a character with a missing
// sword renders without it rather than failing to render.
const MeshData& sharedHeldItemMesh(size_t catalogueIndex);

// Places one held item on a posed character. Returns false when the item has
// no mesh, which is the ordinary "asset not installed" answer rather than an
// error.
bool placeHeldItem(size_t catalogueIndex, bool sheathed, const HumanoidVariant& variant,
                   const Mat4 jointWorld[kJointCount], HeldItemPlacement& out);

// Whether a wearable row is a held item at all.
bool isHeldItem(size_t catalogueIndex);

// The held-item half of a catalogue row, or null when that row is a garment.
const HeldItemDef* heldItemDef(size_t catalogueIndex);

}  // namespace mge
