#!/usr/bin/env bash
# Embeds the engine's default UI font (Liberation Serif, SIL OFL 1.1 — see
# third_party/fonts/LICENSE-LiberationSerif) as a committed C header, like the
# SPIR-V shaders: the engine must never depend on a host font path (P11 —
# Hebrew coverage travels with the engine, on device and off).
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=third_party/fonts/LiberationSerif-Regular.ttf
OUT=engine/generated/fonts/liberation_serif_regular.h
mkdir -p "$(dirname "$OUT")"

python3 - "$SRC" "$OUT" <<'EOF'
import sys
data = open(sys.argv[1], 'rb').read()
with open(sys.argv[2], 'w') as f:
    f.write('// Generated by scripts/embed-font.sh — do not edit.\n')
    f.write('// Liberation Serif Regular, SIL Open Font License 1.1\n')
    f.write('// (third_party/fonts/LICENSE-LiberationSerif).\n')
    f.write('#pragma once\n#include <cstddef>\n\n')
    f.write('inline constexpr unsigned char k_font_liberation_serif[] = {\n')
    for i in range(0, len(data), 24):
        f.write('    ' + ','.join(str(b) for b in data[i:i+24]) + ',\n')
    f.write('};\n')
    f.write(f'inline constexpr size_t k_font_liberation_serif_size = {len(data)};\n')
print(f'embedded {len(data)} bytes -> {sys.argv[2]}')
EOF
